mongo:
  uri: "${MONGO_URI}"
  database: "users_db"
  timeout: 10
  collection:
    collection_name: "users"

google:
  client_id: "${GOOGLE_CLIENT_ID}"
  client_secret: "${GOOGLE_CLIENT_SECRET}"
  redirect_url: "http://localhost:8765/auth/google/callback"
  google_url_email: "https://www.googleapis.com/auth/userinfo.email"
  google_url_profile: "https://www.googleapis.com/auth/userinfo.profile"

jwt:
  secret: "${JWT_SECRET}"
  expiry: "24h"

server:
  port: "${SERVER_PORT}"